# Activa ZMK Studio
CONFIG_ZMK_STUDIO=y
# Forzar la salida por USB cuando está conectado
CONFIG_ZMK_USB=y
# Habilitar el logging por USB para ver qué pasa si falla (opcional)
CONFIG_ZMK_USB_LOGGING=y
# Activa pantallas nice!view
CONFIG_ZMK_DISPLAY=y

# Mejora la estabilidad del Bluetooth en la v1
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
